# -*- coding: utf-8 -*-
"""FP4_phase2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aC8-QgPDY7Q6kLFNiGOpoIyt89RzFbZQ

## **FP4 PHASE 2**
Here we are implementing FP4 in CNN MNIST Dataset

# Experimental Results in this miniproject
Dataset:
MNIST

Model:
CNN

Parameters:
206,922

Quantization:
FP4-E2M1

Block size:
32

Accuracy:
FP32 : 98.80%
FP4  : 98.45%

Accuracy drop:
0.35%

Best quantization error:
FC1 MAE = 0.00711

Storage simulation:
FP32 file = 811.78 KB
FP4 simulated file = 811.33 KB
(reason: stored as FP32)
"""

# Step 1: Import required libraries

import torch
import torch.nn as nn
import torch.optim as optim

import torchvision
import torchvision.transforms as transforms

from torch.utils.data import DataLoader

import matplotlib.pyplot as plt
import numpy as np

# Check GPU availability

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("Using device:", device)

# Step 2: Download and load MNIST dataset

transform = transforms.Compose([
    transforms.ToTensor()
])


# Training dataset

train_dataset = torchvision.datasets.MNIST(
    root="./data",
    train=True,
    download=True,
    transform=transform
)


# Testing dataset

test_dataset = torchvision.datasets.MNIST(
    root="./data",
    train=False,
    download=True,
    transform=transform
)


print("Training samples:", len(train_dataset))
print("Testing samples:", len(test_dataset))

"""same as before we cant send as a whole so we group into batches"""

# Step 3: Create batches

batch_size = 64


train_loader = DataLoader(
    train_dataset,
    batch_size=batch_size,
    shuffle=True
)


test_loader = DataLoader(
    test_dataset,
    batch_size=batch_size,
    shuffle=False
)


print("Number of training batches:", len(train_loader))
print("Number of testing batches:", len(test_loader))

"""Here we are augmenting the mnist dataset and seeing what is the image in mnist"""

# Step 4: Display sample images

images, labels = next(iter(train_loader))


plt.figure(figsize=(8,8))

for i in range(9):

    plt.subplot(3,3,i+1)

    plt.imshow(images[i].squeeze(), cmap="gray")

    plt.title(f"Label: {labels[i].item()}")

    plt.axis("off")


plt.show()

# Step 5: Define CNN model

class CNN(nn.Module):

    def __init__(self):

        super(CNN,self).__init__()


        self.conv1 = nn.Conv2d(
            in_channels=1,
            out_channels=16,
            kernel_size=3,
            padding=1
        )


        self.conv2 = nn.Conv2d(
            in_channels=16,
            out_channels=32,
            kernel_size=3,
            padding=1
        )


        self.pool = nn.MaxPool2d(2,2)


        self.fc1 = nn.Linear(
            32*7*7,
            128
        )


        self.fc2 = nn.Linear(
            128,
            10
        )



    def forward(self,x):

        x = torch.relu(self.conv1(x))

        x = self.pool(x)


        x = torch.relu(self.conv2(x))

        x = self.pool(x)


        x = x.view(
            x.size(0),
            -1
        )


        x = torch.relu(self.fc1(x))

        x = self.fc2(x)


        return x



model = CNN().to(device)


print(model)

# Step 6: Define loss and optimizer

criterion = nn.CrossEntropyLoss()

optimizer = optim.Adam(
    model.parameters(),
    lr=0.001
)

"""Training the CNN"""

# Step 7: Training loop

epochs = 5


for epoch in range(epochs):

    running_loss = 0.0

    model.train()

    for images, labels in train_loader:

        images = images.to(device)
        labels = labels.to(device)


        # Forward pass

        outputs = model(images)


        loss = criterion(
            outputs,
            labels
        )


        # Backward pass

        optimizer.zero_grad()

        loss.backward()

        optimizer.step()

        running_loss += loss.item()


    print(
        f"Epoch [{epoch+1}/{epochs}], Loss: {running_loss/len(train_loader):.4f}"
    )

# Step 8: Evaluate FP32 model

def evaluate(model):

    model.eval()

    correct = 0
    total = 0


    with torch.no_grad():

        for images, labels in test_loader:

            images = images.to(device)
            labels = labels.to(device)


            outputs = model(images)


            _, predicted = torch.max(
                outputs.data,
                1
            )


            total += labels.size(0)

            correct += (
                predicted == labels
            ).sum().item()



    accuracy = 100 * correct / total

    return accuracy



fp32_accuracy = evaluate(model)


print(
    f"FP32 Accuracy: {fp32_accuracy:.2f}%"
)

# Step 9: Save FP32 model and calculate model size

import os

model_path = "cnn_fp32.pth"

# Save model
torch.save(
    model.state_dict(),
    model_path
)

# Calculate model size
model_size_bytes = os.path.getsize(model_path)

model_size_kb = model_size_bytes / 1024
model_size_mb = model_size_kb / 1024


print("FP32 model saved")

print(f"Model size: {model_size_bytes} bytes")
print(f"Model size: {model_size_kb:.2f} KB")
print(f"Model size: {model_size_mb:.4f} MB")

"""**END OF FP32 BASELINE MODAL**

## STARTING WITH THE FP4 MODAL WHICH WE SHALL COMPARE TO THE FP32 MODAL

First we shall inspect  the weights, their distrubution and parameters
We shall try to understand the following questions

1.How many parameters does our CNN have?

2.What is the range of weight values?

3.Are most weights small or large?

4.How much information will FP4 lose?
"""

# Step 10.1: How many parametrs does our cnn have?

total_params = sum(
    p.numel() for p in model.parameters()
)

trainable_params = sum(
    p.numel() for p in model.parameters()
    if p.requires_grad
)


print("Total parameters:", total_params)
print("Trainable parameters:", trainable_params)

"""multiply 32 by total parametrs and divide by 8 u shall get the modal size"""

# Step 10.2: Display layer information
# Check each layer's weight size
for name, param in model.named_parameters():

    print(
        name,
        " | Shape:",
        param.shape,
        " | Number of values:",
        param.numel()
    )

"""97% memory usage"""

# Find  min and max weight values
# Step 10.3: Find weight ranges

for name, param in model.named_parameters():

    if "weight" in name:

        print("\nLayer:", name)

        print(
            "Minimum:",
            param.min().item()
        )

        print(
            "Maximum:",
            param.max().item()
        )

"""notice that the values remain in -0.7 to 0.7 range it is normal to centre around zero for nueral netwroks"""

# Visualise weight distrubution
# Step 10.4: Plot weight distribution

import matplotlib.pyplot as plt


all_weights = []


for name, param in model.named_parameters():

    if "weight" in name:

        all_weights.extend(
            param.detach()
            .cpu()
            .numpy()
            .flatten()
        )


plt.figure(figsize=(8,5))

plt.hist(
    all_weights,
    bins=100
)

plt.xlabel("Weight value")
plt.ylabel("Frequency")
plt.title("FP32 CNN Weight Distribution")

plt.show()

"""**THE FP4 FLOW**

FP32 weight

     
     ↓
Extract sign, exponent, mantissa

     
     ↓
Convert to FP4-E2M1

     
     ↓
Reconstruct approximate FP32 value

    
     ↓
Calculate error

in FP4 we choose this format
S  = 1 sign bit
EE = 2 exponent bits
M  = 1 mantissa bit

## **START**
"""

# Step 11.1: Create FP4-E2M1 representation table
# This is the complete dictionery of FP4 values whereas FP32 might have millions here only limited 1 values
import torch
import math


def create_fp4_table():

    values = []

    # Sign bit
    for sign in [0, 1]:

        # Exponent bits
        for exponent in range(4):

            # Mantissa bit
            for mantissa in [0, 1]:

                # bias for E2M1
                bias = 1

                if exponent == 0:
                    value = 0
                else:
                    value = (
                        (-1)**sign *
                        (1 + mantissa*0.5) *
                        2**(exponent-bias)
                    )

                values.append(value)


    return sorted(set(values))


# fp4_values = create_fp4_table()

fp4_values = [
    -1.75,
    -1.5,
    -1.0,
    -0.75,
    -0.5,
    -0.25,
    0.0,
    0.25,
    0.5,
    0.75,
    1.0,
    1.5,
    1.75
]


print("Number of FP4 values:", len(fp4_values))

print(fp4_values)

# Step 11.2: FP32 to FP4 quantization


def quantize_fp4(value):

    # find closest FP4 value

    closest = min(
        fp4_values,
        key=lambda x: abs(x-value)
    )

    return closest

test_values = [
    0.4635,
    -0.5589,
    0.12,
    1.7
]


for v in test_values:

    q = quantize_fp4(v)

    print(
        f"{v} --> {q}"
    )

"""Now we ave an error here the expected values were 0.4635 matching to 0.5 but it went to 0 likewise we expected

0.4635 --> 0.5

-0.5589 --> -0.5

0.12 --> 0

1.7 --> 2

This happened because there are no small values like . point values in between the integers -6 to 6

SO WE NEED A BETTER FP4 FORMAT
"""

# Step 11.1: Create FP4-E2M1 representation table
# This is the complete dictionery of FP4 values whereas FP32 might have millions here only limited 1 values
import torch
import math


def create_fp4_table():

    values = []

    # Sign bit
    for sign in [0, 1]:

        # Exponent bits
        for exponent in range(4):

            # Mantissa bit
            for mantissa in [0, 1]:

                # bias for E2M1
                bias = 1

                if exponent == 0:
                    value = 0
                else:
                    value = (
                        (-1)**sign *
                        (1 + mantissa*0.5) *
                        2**(exponent-bias)
                    )

                values.append(value)


    return sorted(set(values))


# fp4_values = create_fp4_table()

fp4_values = [
    -1.75,
    -1.5,
    -1.0,
    -0.75,
    -0.5,
    -0.25,
    0.0,
    0.25,
    0.5,
    0.75,
    1.0,
    1.5,
    1.75
]


print("Number of FP4 values:", len(fp4_values))

print(fp4_values)

# Step 11.2: FP32 to FP4 quantization


def quantize_fp4(value):

    # find closest FP4 value

    closest = min(
        fp4_values,
        key=lambda x: abs(x-value)
    )

    return closest

"""A naive FP4:

preserves range but destroys useful precision

A carefully designed FP4:

preserves the distribution where neural network weights exist
"""

test_values = [
    0.4635,
    -0.5589,
    0.12,
    1.7
]


for v in test_values:

    q = quantize_fp4(v)

    print(
        f"{v} --> {q}"
    )

"""Now we quantise cnn weights using tensors"""

# Step 12.1: Quantize a tensor using FP4

def quantize_tensor_fp4(tensor):

    tensor_np = tensor.detach().cpu().numpy()

    quantized_tensor = np.zeros_like(tensor_np)


    # Convert every value to nearest FP4 value

    for index, value in np.ndenumerate(tensor_np):

        quantized_tensor[index] = quantize_fp4(value)


    return torch.tensor(
        quantized_tensor,
        dtype=torch.float32
    )

# Testing on one layer first
# Step 12.2: Test FP4 quantization on fc1 weights

original_weights = model.fc1.weight.data


fp4_weights = quantize_tensor_fp4(
    original_weights
)


print("Original first 10 weights:")

print(
    original_weights.flatten()[:10]
)


print("\nFP4 first 10 weights:")

print(
    fp4_weights.flatten()[:10]
)

"""WHY IS EVERYTHING BECOMING ZERO ??
LARGE ERROR: This prediction model is too naive it cant differentiate all the values next to zero so we change our methodology from
FP32 to FP4 directly  

we instead change the scaling factor

What is the reason ??
the values in the fp4 table we made are mid range but most of the nueral network values are lcose to 0 so the difference betwen the numbers are calcculated and the closest are considered so the porblem of all zeroeas arise

"""

# Step 12.3: Calculate error

error = torch.mean(
    torch.abs(
        original_weights - fp4_weights
    )
)

print(
    "Mean Absolute Error:",
    error.item()
)

"""That is why the llm fp4 quantise weights unrandomly  they do weight / scale

# Create Scaled FP4 Quantizer
"""

# Step 12.4.1: FP4 quantization with scaling
# We do this scaling to overcome the error porduced during the direct quantisation step
def quantize_tensor_fp4_scaled(tensor):

    tensor = tensor.detach().cpu()


    # Find maximum absolute value

    max_value = torch.max(
        torch.abs(tensor)
    )


    # Calculate scale

    scale = max_value / 1.75


    # Normalize

    normalized_tensor = tensor / scale


    # Quantize normalized values

    quantized_tensor = torch.zeros_like(
        normalized_tensor
    )


    for index, value in np.ndenumerate(
        normalized_tensor.numpy()
    ):

        quantized_tensor[index] = quantize_fp4(value)


    # Convert back to original range

    reconstructed_tensor = (
        quantized_tensor * scale
    )


    return reconstructed_tensor, scale

# Test scaled FP4 quantization

original_weights = model.fc1.weight.data


fp4_scaled_weights, scale = quantize_tensor_fp4_scaled(
    original_weights
)


print("Scale value:")
print(scale.item())


print("\nOriginal first 10 weights:")

print(
    original_weights.flatten()[:10]
)


print("\nFP4 reconstructed first 10 weights:")

print(
    fp4_scaled_weights.flatten()[:10]
)

# Calculate scaled FP4 error

error_scaled = torch.mean(
    torch.abs(
        original_weights -
        fp4_scaled_weights
    )
)


print(
    "Mean Absolute Error after scaling:",
    error_scaled.item()
)

"""Currently we did FP4 + one scale down, It proved less useful os we try BLOCK WISE FP4 QUANTISATION

In blockwise quantisation we do the following steps ,
1. Split each others weights into blocks (32 or 64)
2. Calculate one scale per block
3. Quantise each block seperately
4. Reconstruct weights
5. Compare error


Here each block has its own scale so that
0.002 , 0.0034 like that and

0.3,0.34 has diferent scale

# IMPLEMENT BLOCWISE FP4 QUANTIZER
"""

# Step 12.5.1: Block-wise FP4 quantization

def quantize_tensor_fp4_blockwise(tensor, block_size=32):

    tensor_flat = tensor.detach().cpu().flatten()


    quantized_flat = torch.zeros_like(
        tensor_flat
    )


    scales = []


    # Process blocks

    for i in range(0, len(tensor_flat), block_size):

        block = tensor_flat[i:i+block_size]


        # Calculate scale for this block

        max_value = torch.max(
            torch.abs(block)
        )


        if max_value == 0:
            scale = 1.0

        else:
            scale = max_value / 1.75


        scales.append(scale)


        # Normalize block

        normalized_block = block / scale


        # Quantize values

        quantized_block = torch.zeros_like(
            normalized_block
        )


        for index, value in enumerate(normalized_block):

            quantized_block[index] = quantize_fp4(
                value.item()
            )


        # Restore scale

        reconstructed_block = (
            quantized_block * scale
        )


        quantized_flat[i:i+block_size] = reconstructed_block


    return (
        quantized_flat.reshape(tensor.shape),
        scales
    )

"""**Divide weights into small blocks, find a scale for each block, convert the values inside the block to FP4, then multiply back by the scale.**"""

# Test block-wise FP4

original_weights = model.fc1.weight.data


fp4_block_weights, scales = quantize_tensor_fp4_blockwise(
    original_weights,
    block_size=32
)


print("Number of blocks:", len(scales))

print("\nOriginal first 10 weights:")

print(
    original_weights.flatten()[:10]
)


print("\nBlock FP4 reconstructed first 10 weights:")

print(
    fp4_block_weights.flatten()[:10]
)

# Calculate block-wise error

block_error = torch.mean(
    torch.abs(
        original_weights -
        fp4_block_weights
    )
)


print(
    "Block-wise FP4 MAE:",
    block_error.item()
)

import copy
# To create a copy of the trained model
# Step 13.2: Create FP4 model copy

fp4_model = copy.deepcopy(model)

print("FP4 model created")

"""The blockwise quantisation we did on the find the scale for each block we apply that to every layer"""

# Step 13.3: Quantize all weights


def quantize_model_fp4(model, block_size=32):

    model_fp4 = copy.deepcopy(model)


    scales_dict = {}


    for name, param in model_fp4.named_parameters():

        # Only quantize weights
        # Keep biases unchanged

        if "weight" in name:

            original_shape = param.data.shape


            quantized_weight, scales = quantize_tensor_fp4_blockwise(
                param.data,
                block_size
            )


            param.data = quantized_weight


            scales_dict[name] = scales


            print(
                name,
                "quantized",
                "| Blocks:",
                len(scales)
            )


    return model_fp4, scales_dict

fp4_model, fp4_scales = quantize_model_fp4(
    model,
    block_size=32
)

# Step 14: Evaluate FP4 model

fp4_accuracy = evaluate(fp4_model)


print(
    f"FP4 CNN Accuracy: {fp4_accuracy:.2f}%"
)

print(
    f"FP32 Accuracy: {fp32_accuracy:.2f}%"
)

print(
    f"FP4 Accuracy: {fp4_accuracy:.2f}%"
)


accuracy_drop = fp32_accuracy - fp4_accuracy


print(
    f"Accuracy Drop: {accuracy_drop:.2f}%"
)

"""That is an 8× reduction in weight precision.

But the model accuracy changed only:

98.80−98.45=0.35%

which is extremely small.
"""

# calculating memory reduction
# Step 15.1: FP32 memory calculation

total_params = sum(
    p.numel()
    for p in model.parameters()
)


fp32_bits = total_params * 32

fp32_bytes = fp32_bits / 8

fp32_kb = fp32_bytes / 1024


print("Total parameters:", total_params)

print(
    f"FP32 storage: {fp32_kb:.2f} KB"
)

# Step 15.2: FP4 weight storage

fp4_bits = total_params * 4

fp4_bytes = fp4_bits / 8

fp4_kb = fp4_bytes / 1024


print(
    f"FP4 weight storage: {fp4_kb:.2f} KB"
)

# Step 15.3: Scale storage calculation

total_scales = 0


for layer, scales in fp4_scales.items():

    total_scales += len(scales)


print(
    "Total number of scales:",
    total_scales
)
scale_bits = total_scales * 32

scale_bytes = scale_bits / 8

scale_kb = scale_bytes / 1024


print(
    f"Scale storage: {scale_kb:.2f} KB"
)

total_fp4_kb = fp4_kb + scale_kb


print(
    f"Total FP4 storage: {total_fp4_kb:.2f} KB"
)


compression = fp32_kb / total_fp4_kb


print(
    f"Compression ratio: {compression:.2f}x"
)

# compression is not exactly egth due to weight storage

# Step 16.1: Layer-wise FP4 quantization error


def calculate_layer_error(original_model, fp4_model):

    errors = {}


    for (name1, param1), (name2, param2) in zip(
        original_model.named_parameters(),
        fp4_model.named_parameters()
    ):

        if "weight" in name1:

            error = torch.mean(
                torch.abs(
                    param1.data - param2.data
                )
            )


            errors[name1] = error.item()


    return errors



layer_errors = calculate_layer_error(
    model,
    fp4_model
)


for layer, error in layer_errors.items():

    print(
        layer,
        "MAE:",
        error
    )

# STEP 17: Save FP4 model

torch.save(
    fp4_model.state_dict(),
    "cnn_fp4.pth"
)


print("FP4 model saved")

import os


fp32_size = os.path.getsize(
    "cnn_fp32.pth"
)

fp4_size = os.path.getsize(
    "cnn_fp4.pth"
)


print(
    f"FP32 file size: {fp32_size/1024:.2f} KB"
)


print(
    f"FP4 file size: {fp4_size/1024:.2f} KB"
)

"""WE GOT THE SAME FILE SIZE BECAUSE

this is software ...pytorch saves the files as 32 bit floating point itself but in real fp4 hardware we can save the memory by 6.4x itmes smalles
"""